### PR TITLE
various corrections, clarifications, and suggested structure changes

### PR DESCRIPTION
**Pull request by GrantPax**
I did a `git rebase -i HEAD~7` to fix the commit requests on this branch. I did notice Peter committed one fix to the navigation since I started. Do you need me to figure out how to include that commit?

### CODE REVIEW

**Comment by bjhargrave** [comment]
I don't recall closing this, but I suspect that github did when I deleted the master branch from the repo. I moved the repo over to github pages, so all the work is on the gh-pages branch now. So you will need to redo you changes over there in the new directory structure (_source => /).

I would also suggest that if the changes are unrelated that you use a separate PR for each change so the change can be either accepted or rejected independently. If you put a bunch of unrelated changes in a single PR, then one rejected changes means the entire PR is rejected. Along these lines, you should use a separate branch per PR so you can rework a fix if necessary independently of other PRs.

**Comment by GrantPax** [comment]
I didn't understand the atomicity needed to be at the PR level. I thought commits were functionally atomic. I hate being ignorant. Thank you for the guidance.

**Comment by bjhargrave** [comment]
Commits are atomic. But they are in a sequence. So you can't take some from a PR and reject the others. So for unrelated fixes if you use separate PRs they can be individually considered.

**Comment by GrantPax** [comment]
That makes sense to me. Thank you.

More inexperience is dogging me. Do I need to redo my changes manually? I will if that’s the only (or only sensible) way to do it.

**Comment by bjhargrave** [comment]
Yes. You will need to reapply them manually to the new gh-pages branch.

**Comment by GrantPax** [comment]
Ok.

**Pull request closed without merging**
