### PR TITLE
Improved third paragraph

### PR DESCRIPTION
**Pull request by umakanthpai**

### CODE REVIEW

**Comment by bjhargrave** [comment]
Please add a Signed-off-by to your commit message. See https://github.com/osgi/osgi.enroute.site/blob/gh-pages/CONTRIBUTING.md#sign-your-work.

**Comment by bjhargrave** [comment]
Bump.

**Comment by pkriens** [comment]
Bump??

**Comment by bjhargrave** [comment]
> Bump??

Trying to attract the attention of the submitter by "bumping" the issue :-)

**Comment by umakanthpai** [comment]
You have really attracted me...but been very busy since past months working
on two projects and I am not very good at GIT, will try to resolve this
soon...but if it is too late please bump it...

On Fri, Feb 19, 2016 at 1:11 PM, BJ Hargrave <notifications@github.com>
wrote:

> Bump??
>
> Trying to attract the attention of the submitter by "bumping" the issue :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osgi/osgi.enroute.site/pull/61#issuecomment-186191145>
> .
>



-- 
Warm Regards

Umakanth Pai
Handy:  0049 01763 6785 661
-----------------------------------

**Pull request closed without merging**
