### PR TITLE
various corrections, clarifications

### PR DESCRIPTION
**Pull request by GrantPax**
I tried to keep the commits atomic. I messed up the signatures until the end. If I need to sign something, I will. If this helps to cover everything: Signed-off-by: Grant Pax <grant@fwep.twostewards.com> for all commits in this pull request. As I mention in one commit, I have a feature request into the GitHub for Mac folks.

### CODE REVIEW

**Comment by GrantPax** [comment]
Forgot. All commits in this pull request are mirrored in the GitHub-only build.

**Comment by bjhargrave** [comment]
Some problems here. There is a merge commit which should not be here. You should just have your commits ideally rebased on the tip of master in the main repo but the rebasing is not necessary unless the PR wont merge cleanly.

Also not all of the commits contain the necessary Signed-off-by comments. Each individual commit message must include it. Putting it in the PR comments is not sufficient as the PR comments are not in the repo as a permanent part of the work.

Please amend your commit comments and remove the merge commit.

**Comment by GrantPax** [comment]
Ok. I’ll ask if I can’t figure how to fix the mess. Per our last, I’ll submit from the branch.

**Comment by GrantPax** [comment]
PR #22 submitted to replace this request

**Pull request closed without merging**
