### PR TITLE
A bunch of changes that I believe should benefit the developers

### PR DESCRIPTION
**Pull request by daghanacay**
Most of the changes are minor and in place. so it should be easy to review. However changes to tutorial-base/400-run.md and tutorial-base/700-deploy are cross dependent and should be viewed carefully.

Basically I tried to create the tutorial follow  the flow of API-provider-application. I removed much content in the 400-run page that introduce test:eval.

There is also one commit which requires the admin to respond and answer if deemed important. this is the last section of tutorial_base/500-dependencies.html Peter originally suggested to move this to bnd.bndtools.org 

Thanks in advance and I hope my changes do not create a lot of problem and confusion.

### CODE REVIEW

**Comment by bjhargrave** [comment]
None of your commit messages have the required `Signed-off-by` comments. Please amend all of the commits so that their commit messages include the required `Signed-off-by`. Thanks.

**Comment by daghanacay** [comment]
Hi bj,

I have added the signed-off-by I have also squashed the three commits regarding pages 400-run and 700-deploy. please let me know if you need more changes.

thanks

**Comment by bjhargrave** [comment]
> I have added the signed-off-by

Thanks. I'll be on vacation for a week, so I will leave it to @pkriens to review.

**Comment by pkriens** [comment]
Thanks! I've taken the parts that I fully agreed with. Since some of the later changes were (or at least felt) too big I've not included them. I understand, this is a judgement call but for now I am in bugfixing mode on this project and cannot spent the time to oversee all implications of such big changes.

**Comment by daghanacay** [comment]
@pkriens thanks. I understand large changes is not necessary at this stage. Thanks for accepting some. Please let me know if my time can be spent more effectively in other parts of enroute. I can do coding as well.

**Comment by pkriens** [comment]
Thanks, I really do appreciate your feedback. If you really want to help, then the most pressing issues are:

1) To make the bundles in https://github.com/osgi/osgi.enroute.bundles <https://github.com/osgi/osgi.enroute.bundles> more reliable + document. This mainly means adding test cases.
2) Extend the service catalog. This requires a description and an example
3) bnd(tools) documentation http://bnd.bndtools.org/chapters/850-macros.html <http://bnd.bndtools.org/chapters/850-macros.html> and http://bnd.bndtools.org/chapters/820-instructions.html <http://bnd.bndtools.org/chapters/820-instructions.html>. These have some text but this is mostly pasted code that needs to be described.

Thanks, for the help! Kind regards,

	Peter Kriens

**Comment by daghanacay** [comment]
Hi Peter,

I am most eligible to do option 1, I will pick up one of the bundles and
start writing code on it. One question: would you mind if I use Mockito for
mocking?

Benefit:
I think it makes a good case to show how we can integrate mockito to OSGi
for mocking.
Has many benefits especially the use @InjectMock annotation (to inject
mocks in place of services that are using @reference annotation).
Brings osgi tests closer to accepted practices for testing thus reducing
the adoption threshold

Drawback:
it adds additional complexity.

Please let me know what you think.

Cheers
-Daghan

**Comment by pkriens** [comment]
Mockito is fine with me. I think it is part of the distribution already?

Kind regards,

	Peter Kriens

**Pull request closed without merging**
