### PR TITLE
Suggested corrections / improvements + a few questions about configuration

### PR DESCRIPTION
**Pull request by dleangen**
All changes are in one single commit this time. :-)

### CODE REVIEW

**Comment by dleangen** [comment]
Well, I (re-re-re)read the spec. I am quite sure I am not doing anything wrong, and I am quite sure that my Configuration should get applied to my component. I strongly suspect that my problem is (still) related to this:

  https://groups.google.com/forum/#!topic/bndtools-users/iClisFYreDI

I am currently asking for help on the Felix list. If this is indeed a bug that needs to be filed, I will try to widdle it down to a sample project.

**Comment by pkriens** [comment]
The problem you're referring to is investigated by David Jencks. I saw an ordering effect. He tried my setup but could not see it. This was the mail:

I think I nailed down the issue, my guess it is in Felix SCR and suggest you file an issue.

The ordering problem is caused by:

	1: a component C with configuration policy require (no dependency on config admin)
	2: a component Z that sets an instance for bundle 1’s component (dependency on config admin)
	3: config admin
	4: scr

Any other ordering works :-)

About the code you submitted, some tips. Next time please try to bring it down to a smaller sample. If you have such a problem you invariably find the problem by removing code in chunks until you see a change in behavior. The nice thing is then that at the end it is obvious what is going on. It also helps in this phase to aggressively refactor the code so you use 1 character names that are easier to separate then very similar (or in your case identical messages/names).

Included are the bundles that fail, you might want to add them to the Felix SCR issue. They include their source code.

Kind regards,

	Peter Kriens


c bundle:
=========
package csample;

package csample;

import java.io.IOException;
import java.util.Map;

import org.osgi.framework.InvalidSyntaxException;

import aQute.bnd.annotation.component.Activate;
import aQute.bnd.annotation.component.Component;
import aQute.bnd.annotation.component.ConfigurationPolicy;

@Component(
                name = "sample.cm.require",
                configurationPolicy = ConfigurationPolicy.require,
                immediate = true)
public class C {

    @Activate
    public void startup(Map<String, Object> props) throws InvalidSyntaxException, IOException {
        String name = (String) props.get("sample.cm.require.name");        
        System.out.println("C : startup -> " + name);
    }
}

z bundle:
=========
package zsample;

import java.io.IOException;
import java.util.Dictionary;
import java.util.Hashtable;

import org.osgi.framework.InvalidSyntaxException;
import org.osgi.service.cm.Configuration;
import org.osgi.service.cm.ConfigurationAdmin;
import org.osgi.service.component.ComponentContext;

import aQute.bnd.annotation.component.Activate;
import aQute.bnd.annotation.component.Component;
import aQute.bnd.annotation.component.Deactivate;
import aQute.bnd.annotation.component.Reference;

@Component(immediate = true)
public class Z {

	private ConfigurationAdmin configAdmin;

	@Activate
	public void startup(ComponentContext ctx) throws InvalidSyntaxException, IOException {
		System.out.println("Z Startup");
		Dictionary<String, Object> props = new Hashtable<>();

		String pid = "sample.cm.require";
		Configuration config = configAdmin.createFactoryConfiguration(pid, null);

		props.put("sample.cm.require.name", "from Z");

		config.update(props);
	}

	@Deactivate
	public void shutdown(ComponentContext ctx) {
		System.out.println("Z Shutdown");
	}

	@Reference
	public void setConfigAdmin(ConfigurationAdmin configAdmin) {
		this.configAdmin = configAdmin;
		System.out.println("Z setConfigAdmin");
	}
}


bndrun file:

-runbundles: \
	c;version=latest,\
	z;version=latest,\
	org.apache.felix.configadmin,\
	org.apache.felix.scr

-runfw: org.apache.felix.framework;version='[4.4.1,4.4.1]'
-runee: JavaSE-1.8

**Comment by dleangen** [comment]
Thank you, Peter.

I really hope I am not embarrassing myself (and wasting your time in the process) by missing something stooopid... :-/

But here is the minimal project for which I am still unable to get configuration working, even when changing the order of in runbundles:

  https://github.com/dleangen/scr.debug.test

Note that not only is configuration update not getting applied, but also initial configuration.

**Comment by pkriens** [comment]
I am afraid there is a certain amount of embarrassment :-)

a) You forgot to add the `test.m` bundle to the `-runrequire` of the bnd.bnd file in the `test.i` project. So there was no bundle. I added this bundle and then resolved. Still did not work though ...
b) The `test.m` bundle's activate was never called because nobody was ever using its service. OSGi DS components are by default lazy. When I added `immediate=true` to the `MImpl` component then things worked as expected.

These things happen to me all the time. It might have helped you if you'd looked at XRay. The fact that the `test.m` bundle was missing would have been obvious I think. It would also have shown the lazyness of the M service.

**Comment by dleangen** [comment]
Well, it's not the first time I've been red-faced. ;-P

I ported the changes back into my "real" project, and yes, it works.

So, my problem appears to be a total misunderstanding in terms of what XRay et al was trying to tell me. Otherwise, I would have had better luck. BTW, in my multitude of attempts to make it work, I DID try the above combination, but something else must have been going on at that time.

Anyway, thanks so much!!!! I'll try to return the favour when I can by chipping in.

**Comment by pkriens** [comment]
No problem, just keep providing feedback and I am more than happy to help out.

If you have any ideas how XRay could be improved to show such a problem, let me know

**Comment by dleangen** [comment]
Ok, so what I'll do is close this pull request, retract my questions, and add my comments regarding how, despite using XRay, I missed the solution.

BTW, there were actually 2 problems:
 # I did not catch that my component was throwing an exception
 # Even after finally realising that an exception was being thrown, I did not realise that my component needed to actually be instantiated first (for instance by using immediate=true)

Now that I know, the problem is easy to solve. For those who are not aware (like was the case for me), having better feedback mechanisms probably would have let me to the solution quite quickly.

**Comment by dleangen** [comment]
Oh, neato. Looks like Github added my changes to this pull request, so I don't need to close and create a new one. Cool!

**Comment by bjhargrave** [comment]
Except you have an unnecessary merge commit in here. Can you please rebase your changes to remove the merge commit?

**Comment by dleangen** [comment]
Yes, sorry about that.

Because of the merge, t will be easier (for me) to delete this pull request and create a new one.

**Pull request closed without merging**
