### PR TITLE
Update DTO per post by Peter - Very helpful.

### PR DESCRIPTION
**Pull request by cboecking**
I think Peter's post is helpful and should be more easily readible via the DTO service description.

### CODE REVIEW

**Comment by cboecking** [comment]
I just got an email from github saying that the build failed; however, I cannot find the detailed error message. I ran "jekyll build --safe" against my clone of the project, and it passed. Please let me know if I need to do anything.
Chuck

**Comment by bjhargrave** [comment]
We are having an issue with the update of github-pages to jekyll 3. :-(

**Comment by cboecking** [comment]
I got an error shortly after I submitted the request. It did not say why it
failed. I am trying to get Jekyll 3 installed to tell me what is wrong.


Regards,


Chuck Boecking
512.850.6068 (office and cell)
chuck@chuboe.com
ChuckBoecking.com
chuck.boecking (skype)
@ChuckBoecking
http://www.linkedin.com/pub/chuck-boecking/10/970/17b

**Comment by bjhargrave** [comment]
There is a loop in the processing of `_layouts/service.html` so jekyll runs until it runs out of memory. For example, if you delete this file, the build will finish with some errors about the missing file. But with the file, OOM.

If you have any jekyll _foo_ and can figure out how to fix this, that would be so awesome!

**Comment by bjhargrave** [comment]
Also, reproduce locally, you will need to edit the `Gemfile` to use versio 48 of github-pages and then tune `bundle update` to update the gems for that version.

**Comment by bjhargrave** [comment]
> Also, reproduce locally, you will need to edit the Gemfile to use versio 48 of github-pages and then tune bundle update to update the gems for that version.

I pushed a `gh-pages3` branch with these changes for you to try. Run the build with `bundle exec jekyll build`.

**Comment by cboecking** [comment]
I am confused as to why this is failing because all I did was:

   - fork the repo
   - paste text into one file via the github browser
   - create a pull request

I changed nothing else. There are no links in the text I pasted. I do not
understand how the loop got created. Thoughts?


Regards,


Chuck Boecking
512.850.6068 (office and cell)
chuck@chuboe.com
ChuckBoecking.com
chuck.boecking (skype)
@ChuckBoecking
http://www.linkedin.com/pub/chuck-boecking/10/970/17b

**Comment by bjhargrave** [comment]
You did not cause the failure :-) The issue results from GitHub's recent update of GitHub Pages to use Jekyll 3. Jekyll 3 goes into a loop building the site.

**Comment by cboecking** [comment]
BTW - Tom Watson (from Austin) is a buddy of mine. Small world...

You said that in your first email; however, I read it as "You are not doing
it right per jekyll 3". Sorry for misreading...

Just getting jekyll3 installed on ubuntu is a pain!! Here are the steps it
took for me to get jekyll3 installed (sending for reference). Installing
Ruby2 is most of the below work:
    1  sudo apt-get update
    2  sudo apt-get install git-core curl zlib1g-dev build-essential
libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev
libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev
    3  git clone git://github.com/sstephenson/rbenv.git .rbenv
    4  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
    5  echo 'eval "$(rbenv init -)"' >> ~/.bashrc
    6  exec $SHELL
    7  git clone git://github.com/sstephenson/ruby-build.git
~/.rbenv/plugins/ruby-build
    8  echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >>
~/.bashrc
    9  exec $SHELL
   10  rbenv install 2.2.0
   11  rbenv global 2.2.0
   12  ruby -v
   13  sudo apt-get install make gcc nodejs
...
   20  gem install jekyll
...
   22  git clone https://github.com/cboecking/osgi.enroute.site.git
   23  ll
   24  cd osgi.enroute.site/
...
   28  gem update github-pages (supposed to update to the current version
at github pages - https://help.github.com/articles/using-jekyll-with-pages/)
   29  jekyll build --safe

This produces no errors... Builds in 2 seconds. FYI - I do not know how to
edit the Gemfile to use versio 48 of github-pages and then tune bundle
update to update the gems for that version. I think that is what 'gem
update github-pages' is supposed to do as best I can tell.

Did you see this section:
Turning Jekyll off
<https://help.github.com/articles/using-jekyll-with-pages/>: You can
completely opt out of Jekyll processing by creating a file named .nojekyll
in the root of your Page repository and pushing that file to GitHub. This
should only be necessary if your site uses directories that begin with an
underscore, as Jekyll sees these as special directories and does not copy
them to the final destination.




Regards,


Chuck Boecking
512.850.6068 (office and cell)
chuck@chuboe.com
ChuckBoecking.com
chuck.boecking (skype)
@ChuckBoecking
http://www.linkedin.com/pub/chuck-boecking/10/970/17b

**Comment by pkriens** [comment]
I thought installing ruby on Mavis was hard:-( then again you seem to have succeeded while I'm still stuck 😁

**Comment by bjhargrave** [comment]
Jekyll issues are now solved!

However, your commit message is missing the necessary Signed-off-by. See <https://github.com/osgi/osgi.enroute.site/blob/gh-pages/CONTRIBUTING.md#sign-your-work>. Please amend your commit.

> BTW - Tom Watson (from Austin) is a buddy of mine. Small world...

Nice! @tjwatson is awesome.

**Comment by cboecking** [comment]
Does every commit need this or just the last commit before a pull request?


Regards,


Chuck Boecking
512.850.6068 (office and cell)
chuck@chuboe.com
ChuckBoecking.com
chuck.boecking (skype)
@ChuckBoecking
http://www.linkedin.com/pub/chuck-boecking/10/970/17b

**Comment by bjhargrave** [comment]
> Does every commit need this or just the last commit before a pull request?

Every commit.

**Pull request merged**
