### PR TITLE
Initial commit of Resolution Appnotes

### PR DESCRIPTION
**Pull request by dleangen**
I have tried to capture the current email thread here. I am sure this will evolve.

### CODE REVIEW

**Comment by bjhargrave** [comment]
Your commits include `.resolution-notes.md.swp` which should not be commited. Remove this file.

Your ommits need their commit message to include a `Signed-off-by` as required by CONTRIBUTING.

Also, please remove the merge commit. You are only adding a new file so there is no need for anything but a single commit.

**Comment by bjhargrave** [comment]
> I know you are busy, so I apologise for taking up your time, but I need your help. My knowledge of the git model seems to be lacking a bit.
> 
> When I try to make such changes as requested, if I change the history in git in any way after I have already pushed my commits to (my) github, the result includes this kind of double commit and merge. In this case, when I noticed I forgot (again!) the signoff, I did a "git commit --amend --signoff" to amend my commit, and the result is what you see above (excluding my accidental commit of the swp file).
> 

You can amend the tip commit. You can rebase interactively to remove/edit earlier commits.

Once you change the commit history like this, you will need to push force you branch to your fork. The PR will pick up your modified branch.

> Question: in git, is this inevitable? (It sure seems so to me...)
> 
>     If so, then wouldn't the only way to resolve these issues be to close this PR and create a new one on a new branch?

No need to close the PR. Just modify the contents (commits) of your branch and push force the changes. The PR will see this.

> 
>     If not, are you able to point me to some docs that explain this exact problem? The references I used are what led me to this outcome.
> 
> In the meantime, I'll continue to play around with git to see if I can stumble across a method that will provide the right results.

**Comment by dleangen** [comment]
Ok, thanks! That worked. I get it now. :-)

**Comment by bjhargrave** [comment]
@pkriens, please review and merge.

**Comment by pkriens** [comment]
I've made some changes, please review. I think you missed the fact that in my opinion it is _impossible_ to run time resolve because of the optionality problem. I've never heard a possible answer to this problem from the advocates of runtime resolving though they do not seem to give up their position ...

Anyway, feel free to edit.

**Comment by dleangen** [comment]
Thanks for cleaning up the notes, Peter! Very nice!

**Comment by cschneider** [comment]
I am a bit confused about the terms resolving and resolution. 
Resolution is defined as  ..  process of determining a network of resources in a system such that
the requirements and capabilities declared by the resources resolve to a solution.
Still the button on the UI to do the resolution is called resolve. 
In the dictionary I only find resolution as a noun not as a verb.

So I wonder if it could be better described as resolving is the process of wiring a bundle or a number of bundles... and resolution is basically the same as the  solution mentioned in the second definition.

**Comment by pkriens** [comment]
The resolution is the result of the resolve process: a set of wires. I.e. in the meaning of ‘a satisfactory resolution of the problem: solution to, answer to, end to, ending to, settlement of, conclusion to.’

In my text I think I define this correctly.

Kind regards,

	Peter Kriens

**Comment by cschneider** [comment]
A second problem is with the two schools of thought about when we should create the resolution.
Peter declares that runtime resolution is not possible without giving any proof for it. In fact runtime resolution is done in the runtimes from paremus and karaf proving that it is in fact possible and working. Of course the result can change when the input changes but in practice it is proven to work in the relevant cases.

I am also missing the middle way that I described. Creating the resolution at build time. I have tested this approach in an example project and the results are pretty good. The approach to resolve at build time means that during snapshot builds you always get a new resolution. If you depend on snapshots the result may even be broken which is good as it then fails your build and you get an early warning. On the other hand in many cases the resolution will be fine even if the snapshot you depend on has changed. In these cases you get a build that refelects the newest changes which is
needed in any devops environment. You do not want to involve a manual step in these builds.
On the other hand the resolve is only done during the build so when you create a release in maven the resolution will not change. So at runtime you will always have a stable and predictable system.

**Comment by cschneider** [comment]
@pkriens Fully agree with your definitons of resolve and resolution. So I think the page should be fixed accordingly.

**Comment by dleangen** [comment]
Hi Christian,

Sorry for taking so long to reply. Thank you very much for sharing your thoughts!

I would suggest, as Peter always does, if you feel strongly about changing the text, why don't you submit a PR? :-)

Cheers,
=David

**Comment by cschneider** [comment]
I will create a pull request.

**Pull request merged**
