### PR TITLE
a few changes from proofing

### PR DESCRIPTION
**Pull request by GrantPax**
I’m doing a small change set just so we get a feel for each other. If
I’m off in my contributions, set me straight.

### CODE REVIEW

**Comment by bjhargrave** [comment]
One quick procedural issue: Your commit messages must include a Signed-off-by. See <https://github.com/osgi/osgi.enroute.site/blob/master/CONTRIBUTING.md>.

**Comment by bjhargrave** [comment]
Otherwise it seems ok. I will let @pkriens also comment on this.

**Comment by GrantPax** [comment]
Sorry. Do I kill the PR and resubmit?

**Comment by bjhargrave** [comment]
> Sorry. Do I kill the PR and resubmit?

No need to do that. Just use `git commit --amend` to edit your commit message. (In the future, use `git commit -s` to add the Signed-off-by.) Then do `git push --force` to update your fork. This PR will automatically pick up the updated commit.

**Comment by GrantPax** [comment]
Ok. I think I did it correctly. Let me know if I goofed it.

Thanks for your patience.

**Comment by bjhargrave** [comment]
> Ok. I think I did it correctly. Let me know if I goofed it.

You did it right!

**Comment by GrantPax** [comment]
Whew. I’m a bull in many china shops. Glad I didn’t break anything (yet).

**Comment by pkriens** [comment]
Thanks! Seems you had to do a lot of work to get this in, let's hope next time the ratio can be more productive :-)

Again, thanks.

**Comment by GrantPax** [comment]
The life of a greenhorn. Glad to help.

In general, would you prefer I submit PRs from a branch? Either way works for me.

**Comment by bjhargrave** [comment]
> would you prefer I submit PRs from a branch

Using a branch for each discreet PR can be useful since the work in the PR can need rework which can be hard if later PRs are also submitted from the same branch.

**Comment by GrantPax** [comment]
That makes sense to me. So I’ll let others rebase/merge. Once they’ve asked for rework or more work (on the PR based on a dedicated branch) and made their final decisions, I’ll just pull and go on from there. 

Thank you.

**Pull request merged**
