### PR TITLE
workspace - one-liner start

### PR DESCRIPTION
**Pull request by paulvi**
see also http://stackoverflow.com/questions/6941889/is-it-safe-to-shallow-clone-with-depth-1-create-commits-and-pull-updates-aga

### CODE REVIEW

**Comment by bjhargrave** [comment]
This is wrong. The point of the command is to _NOT_ be connected to the remote repo. Your clone command leave the checkout connected to the remote repo. The existing comments just fetch the contents from the remote repo and check it out into the workspace not as a branch. We deliberately do not use clone.

**Comment by pkriens** [comment]
This is moot anyway because bndtools 3.2 will be able to do this from withing Bndtools!

**Comment by paulvi** [comment]
@pkriens by moot do you mean "a hypothetical case that law students argue as an exercise", 
i.e. next version of the tutorial will not have this?

**Comment by pkriens** [comment]
@paulvi  correct, in Bndtools 3.2 we have a 'New Bndotols workspace' command that takes care of the git commands.

**Pull request closed without merging**
