### PR TITLE
Update prerequisites to avoid java 9 and to install bndtools from eclipse market place

### PR DESCRIPTION
**Pull request by YpeKingma**
This is to avoid these issues:

https://github.com/osgi/osgi.enroute/issues/63
https://github.com/osgi/osgi.enroute/issues/52
https://github.com/osgi/osgi.enroute/issues/47

I did not rebuild the site to check that the site builds normally, I'm hoping that these changes are simple enough.

### CODE REVIEW

**Comment by YpeKingma** [comment]
I can see both sign offs here when clicking the three dot button after the first line of each commit message above.
I generated them with Ctrl-S in git gui, I would hope that follows the standard. In case something is wrong, please let me know.

**Comment by bjhargrave** [comment]
> I can see both sign offs

Yes, they look good to me. 

I got similarly mistaken when reviewing a different PR in my phone. The UI on a phone browser hid the full commit text, so I thought the contributor had failed to sign off when they had.

**Comment by timothyjward** [comment]
> I can see both sign offs

Apologies - it turns out that the GitHub UI isn't always my friend!

**Comment by YpeKingma** [comment]
No problem at all. Thank you both.  :)

**Pull request merged**
